import imageLoader from 'libs/imageLoader'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Welcome to my Dev Garden
        </h1>

        <Link href={'/vault/📁developer'}>
          <a > 
            <Image 
              loader={imageLoader}
              unoptimized
              src="/pywriter-logo-v1@2x.svg" 
              alt="There a Will There a Website Logo" 
              width={72} height={32} 
            />

            Developer Notes
          </a>
        </Link>
        
        <Link href={'/vault/📁shower_thoughts'}>
          <a>🚿 Shower Thoughts</a>
        </Link>

      </main>
    </div>
  )
}

export default Home
