import { SearchFuse } from 'components/SearchFuse'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { RiPlantFill } from "react-icons/ri";
import { RecentNotes } from "components/RecentNotes";
import styles from 'styles/Home.module.css'



const Home: NextPage = () => {


  return (
    <div className={styles.container}>
      <Head>
        <title>{process.env.NEXT_PUBLIC_TITLE}</title>
        <meta name="notes that are watered and groomed over time" content="Generated by William Chorski" />
        <link rel="icon" href="/favicon.ico" />
        <script async defer data-website-id="51cc10c2-9579-49b6-99d4-15f94e103850" src="https://analytics.williamusic.com/umami.js"></script>
      </Head>

      <main className={styles.main}>

        <h1>{process.env.NEXT_PUBLIC_TITLE}</h1>
        <h2 className={styles.title}>
          {process.env.NEXT_PUBLIC_SUBTITLE}
        </h2>

        <p>umami id: {process.env.NEXT_PUBLIC_UMAMI_WEBSITE_ID}</p>
        <p>umami src: {process.env.NEXT_PUBLIC_UMAMI_SRC}</p>
        <button id="signup-button" className="button umami--click--signup-button">Umami analytics btn</button>

        <section className="pressStart">

          <Link href='/vault'>
            <a><RiPlantFill /></a>
          </Link>
        </section>

        <SearchFuse />

        <hr />

        <RecentNotes />


      </main>
    </div>
  )
}



export default Home
